/**
 * GET /api/pdf-content?subject=<key>&bab=<id>[&page=<n>]
 *
 * Serves pre-rendered PDF-companion page images, gated by the same
 * auth check as /api/content. Files live in /content-private next to
 * the chapter HTML, outside the public/ output directory — this
 * endpoint is the only path to them, same as /api/content.
 *
 * Omit `page` to get { pageCount } instead of an image, so the client
 * knows how many pages exist before requesting any of them by number.
 * Pages are named <bab>.pdf.<n>.png, 1-indexed, generated by a local
 * render step (see content-private/<subject>/<bab>.pdf-pages.html) —
 * not rendered on demand here.
 */
const fs = require('fs');
const path = require('path');
const { verifyToken, getBearerToken } = require('./_auth');

const SAFE_SEGMENT = /^[a-z0-9-]+$/;

module.exports = async function handler(req, res) {
  if (req.method !== 'GET') {
    res.status(405).json({ success: false, message: 'Method not allowed.' });
    return;
  }

  const payload = verifyToken(getBearerToken(req));
  if (!payload || payload.r !== 'student') {
    res.status(401).json({ success: false, message: 'Akses ditolak — login & paket aktif diperlukan.' });
    return;
  }

  const subject = String(req.query.subject || '');
  const bab = String(req.query.bab || '');
  if (!SAFE_SEGMENT.test(subject) || !SAFE_SEGMENT.test(bab)) {
    res.status(400).json({ success: false, message: 'Permintaan tidak valid.' });
    return;
  }

  const dir = path.join(process.cwd(), 'content-private', subject);
  const prefix = bab + '.pdf.';

  let pageCount = 0;
  try {
    pageCount = fs.readdirSync(dir).filter((f) => f.startsWith(prefix) && f.endsWith('.png')).length;
  } catch (err) {
    pageCount = 0;
  }

  if (pageCount === 0) {
    res.status(404).json({ success: false, message: 'Materi PDF tidak ditemukan.' });
    return;
  }

  if (!req.query.page) {
    res.status(200).json({ success: true, pageCount });
    return;
  }

  const page = parseInt(req.query.page, 10);
  if (!Number.isInteger(page) || page < 1 || page > pageCount) {
    res.status(400).json({ success: false, message: 'Halaman tidak valid.' });
    return;
  }

  const filePath = path.join(dir, `${bab}.pdf.${page}.png`);
  try {
    const buf = fs.readFileSync(filePath);
    res.setHeader('Content-Type', 'image/png');
    res.setHeader('Cache-Control', 'private, no-store');
    res.status(200).send(buf);
  } catch (err) {
    res.status(404).json({ success: false, message: 'Halaman tidak ditemukan.' });
  }
};
